
menu.ap_slot_config.title=Slotkonfiguration
menu.ap_slot_config.registeredslots=Registrierte Slots

menu.ap_slot_config.identifier=Identifikator
menu.ap_slot_config.slot_name=Slotname
menu.ap_slot_config.game=Spiel
menu.ap_slot_config.connected=Verbunden

menu.ap_slot_config.refreshslots=Slots neu laden
menu.ap_slot_config.connectslot=Slotverbindung öffnen
menu.ap_slot_config.disconnectslot=Slotverbindung trennen
menu.ap_slot_config.deleteslot=Slot löschen

menu.ap_slot_config.slot_identifier=Slotidentifikator
menu.ap_slot_config.slot_pass=Slotpasswort
menu.ap_slot_config.slot_address=Slotaddresse
menu.ap_slot_config.game_name=Spielname

menu.ap_slot_config.text_only_check=Slot ist Text-Only
menu.ap_slot_config.receive_chat_check=Chatnachrichten vom AP-Server empfangen
menu.ap_slot_config.hint.receive_chat_check=Wenn diese Option deaktiviert ist sendet der Server dem Clienten keine Chatnachrichten mehr, was Bandbreite sparen kann.
menu.ap_slot_config.forward_to_gmod_chat=AP-Chat zu GMod-Chat weiterleiten
menu.ap_slot_config.forward_to_ap_chat=GMod-Chat zu AP-Chat weiterleiten
menu.ap_slot_config.deathlink_check=Deathlink-Signale erhalten

menu.ap_slot_config.updateslot=Slot hinzufügen/modifizieren

menu.ap_slot_config.hint.identifier=Als was GMod den Slot kennt. Nutzt den Slotnamen wenn nichts eingegeben wird.
menu.ap_slot_config.hint.slotname=Als was Archipelago den Slot kennt.
menu.ap_slot_config.hint.password=Das Passwort dieses Slots.
menu.ap_slot_config.hint.game=Der Name des Spiels welches dieser Slot spielt. Wenn dieses Feld leergelassen wird verbindet sich GMAP also ein text-only Slot und greift den Namen des Spiels automatisch. Nachdem die Verbindung getrennt und neu hergestellt wird können Locations gesendet werden.
menu.ap_slot_config.hint.address=Die Addresse des Archipelago Servers mit GMod sich verbinden soll. Benutzt automatisch ws://localhost:38281 wenn nichts eingegeben wird. An Adressen die ohne Portnummer wird automatisch :38281 angehängt. Wenn nur eine Nummer zwischen 1024 und 65565 eingegeben wird die Adresse automatisch zu einer archipelago.gg-Addresse vervollständigt.
menu.ap_slot_config.hint.deathlink=Erlaubt es diesem Slot DeathLink-Signale zu empfangen. Sie werden nur empfangen, Spieler sterben nicht wenn ein Signal empfangen wird und Tode senden keine Signale.