
menu.ap_slot_config.title=Slotkonfiguration
menu.ap_slot_config.registeredslots=Registrierte Slots

menu.ap_slot_config.identifier=Identifikator
menu.ap_slot_config.slot_name=Slotname
menu.ap_slot_config.game=Spiel
menu.ap_slot_config.connected=Verbunden

menu.ap_slot_config.refreshslots=Slots neu laden
menu.ap_slot_config.connectslot=Slotverbindung öffnen
menu.ap_slot_config.disconnectslot=Slotverbindung trennen
menu.ap_slot_config.deleteslot=Slot löschen

menu.ap_slot_config.slot_identifier=Slotidentifikator
menu.ap_slot_config.slot_pass=Slotpasswort
menu.ap_slot_config.slot_address=Slotaddresse
menu.ap_slot_config.game_name=Spielname

menu.ap_slot_config.text_only_check=Slot ist Text-Only
menu.ap_slot_config.receive_chat_check=Chatnachrichten vom AP-Server empfangen
menu.ap_slot_config.forward_to_gmod_chat=AP-Chat zu GMod-Chat weiterleiten
menu.ap_slot_config.forward_to_ap_chat=GMod-Chat zu AP-Chat weiterleiten
menu.ap_slot_config.deathlink_check=Deathlink-Signale erhalten

menu.ap_slot_config.updateslot=Slot hinzufügen/modifizieren
