
menu.ap_slot_config.title=Slot Configurator
menu.ap_slot_config.registeredslots=Registered Slots

menu.ap_slot_config.identifier=Identifier
menu.ap_slot_config.slot_name=Slot Name
menu.ap_slot_config.game=Game
menu.ap_slot_config.connected=Connected

menu.ap_slot_config.refreshslots=Refresh Slots
menu.ap_slot_config.connectslot=Connect Slot
menu.ap_slot_config.disconnectslot=Disconnect Slot
menu.ap_slot_config.deleteslot=Delete Slot

menu.ap_slot_config.slot_identifier=Slot Identifier
menu.ap_slot_config.slot_pass=Slot Password
menu.ap_slot_config.slot_address=Slot Address
menu.ap_slot_config.game_name=Game Name

menu.ap_slot_config.text_only_check=Slot is Text-Only
menu.ap_slot_config.receive_chat_check=Receive Chat Messages from the AP Server
menu.ap_slot_config.hint.receive_chat_check=When this is disabled, the server won't send chat messages to this slot at all, which can cut down on unnecessary bandwidth usage if you're connected with multiple slots or don't need to receive chat messages for any other reason.
menu.ap_slot_config.forward_to_gmod_chat=Forward AP Chat to GMod Chat
menu.ap_slot_config.forward_to_ap_chat=Forward GMod Chat to AP Chat
menu.ap_slot_config.deathlink_check=Receive Deathlink Signals

menu.ap_slot_config.updateslot=Add/Modify Slot

menu.ap_slot_config.hint.identifier=This is what GMod knows the slot as. Will use the Slot Name if left empty.
menu.ap_slot_config.hint.slotname=This is what Archipelago knows the slot as.
menu.ap_slot_config.hint.password=The slots password.
menu.ap_slot_config.hint.game=The name of the game this slot is playing, if left empty GMAP will connect as a text-only slot and get the name from the server automatically, but you'll have to disconnect and reconnect to be able to send locations. 
menu.ap_slot_config.hint.address=The Address of the Archipelago Server you want to connect to. Will automatically use ws://localhost:38281 if left empty. An address without a Port Number at the end will automatically have :38281 added to it. A Port Number between 1024 and 65565 will be autocompleted to an archipelago.gg address.
menu.ap_slot_config.hint.deathlink=Makes this slot receive DeathLink signals. Does not actually kill players when a DeathLink is received or send a DeathLink when a player dies.
 