
menu.ap_slot_config.title=Slot Configurator
menu.ap_slot_config.registeredslots=Registered Slots

menu.ap_slot_config.identifier=Identifier
menu.ap_slot_config.slot_name=Slot Name
menu.ap_slot_config.game=Game
menu.ap_slot_config.connected=Connected

menu.ap_slot_config.refreshslots=Refresh Slots
menu.ap_slot_config.connectslot=Connect Slot
menu.ap_slot_config.disconnectslot=Disconnect Slot
menu.ap_slot_config.deleteslot=Delete Slot

menu.ap_slot_config.slot_identifier=Slot Identifier
menu.ap_slot_config.slot_pass=Slot Password
menu.ap_slot_config.slot_address=Slot Address
menu.ap_slot_config.game_name=Game Name

menu.ap_slot_config.text_only_check=Slot is Text-Only
menu.ap_slot_config.receive_chat_check=Receive Chat Messages from the AP Server
menu.ap_slot_config.forward_to_gmod_chat=Forward AP Chat to GMod Chat
menu.ap_slot_config.forward_to_ap_chat=Forward GMod Chat to AP Chat
menu.ap_slot_config.deathlink_check=Receive Deathlink Signals

menu.ap_slot_config.updateslot=Add/Modify Slot
